name: Tests By Symfony Version

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*
      - 2.*

jobs:
  test:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3 ]
        os: [ ubuntu-latest ]
        symfony: [ 6.4, 7.0 ]
    env:
      SYMFONY_PHPUNIT_VERSION: 9.6

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Variables
        id: set-variables
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          echo "::set-output name=cacheKeyPath::${{ format('{0}-php{1}-tests-by-symfony-version-{2}-composer-', runner.os, matrix.php, inputs.symfony) }}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-variables.outputs.dir }}
          key: ${{ steps.set-variables.outputs.cacheKeyPath }}${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ steps.set-variables.outputs.cacheKeyPath }}

      - name: Setup PHP
        if: ${{ success() }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: ${{ success() }}
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability stable
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Run PHPUnit
        if: ${{ success() }}
        run: php vendor/bin/phpunit

  dev-test:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3 ]
        os: [ ubuntu-latest ]
        symfony: [ 7.1 ]
    env:
      SYMFONY_PHPUNIT_VERSION: 9.6

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Variables
        id: set-variables
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          echo "::set-output name=cacheKeyPath::${{ format('{0}-php{1}-tests-by-symfony-version-{2}-composer-', runner.os, matrix.php, inputs.symfony) }}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-variables.outputs.dir }}
          key: ${{ steps.set-variables.outputs.cacheKeyPath }}${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ steps.set-variables.outputs.cacheKeyPath }}

      - name: Setup PHP
        if: ${{ success() }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: ${{ success() }}
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability dev
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Run PHPUnit
        if: ${{ success() }}
        run: php vendor/bin/phpunit